insert into categories (name) values ('Clothing - Tops');
insert into categories (name) values ('Food - Meats');
insert into categories (name) values ('Clothing - Bottoms');
insert into categories (name) values ('Food - Grains');
insert into categories (name) values ('Food - Salads');
insert into categories (name) values ('Food - Snacks');
insert into categories (name) values ('Food - Condiments');
insert into categories (name) values ('Kitchen');
insert into categories (name) values ('Home');
insert into categories (name) values ('Fitness');
insert into categories (name) values ('Food - Produce');
insert into categories (name) values ('Food - Snacks');
insert into categories (name) values ('Audio');
insert into categories (name) values ('Kitchen');
insert into categories (name) values ('Food - Snacks');
insert into categories (name) values ('Food - Breakfast');
insert into categories (name) values ('Home');
insert into categories (name) values ('Food - Beverages');
insert into categories (name) values ('Food - Snacks');
insert into categories (name) values ('Food - Pasta');
insert into categories (name) values ('Garden');
insert into categories (name) values ('Food - Salads');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Home');
insert into categories (name) values ('Tools');
insert into categories (name) values ('Food - Bakery');
insert into categories (name) values ('Food - Dairy');
insert into categories (name) values ('Food - Baking');
insert into categories (name) values ('Food - Prepared Foods');
insert into categories (name) values ('Food - Cooking Oil');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Health');
insert into categories (name) values ('Food - Meat');
insert into categories (name) values ('Office');
insert into categories (name) values ('Food - Canned Goods');
insert into categories (name) values ('Food - Meat Substitutes');
insert into categories (name) values ('Food - Bakery');
insert into categories (name) values ('Travel');
insert into categories (name) values ('Clothing - Footwear');
insert into categories (name) values ('Fitness');
insert into categories (name) values ('Food - Seafood');
insert into categories (name) values ('Food - Fresh Produce');
insert into categories (name) values ('Kitchen');
insert into categories (name) values ('Electronics');
insert into categories (name) values ('Kitchen');
insert into categories (name) values ('Home');
insert into categories (name) values ('Office');
insert into categories (name) values ('Food - Snacks');
insert into categories (name) values ('Food - Protein');
insert into categories (name) values ('Food - Snacks');
